var homerow = {
	name: "Home row",
	description: "This will teach you to find the home row.",
	type: "character",
	prompts: ["First find the 'f' key - it will have a bump on it.  Place your left index finger on the 'f' key, and type an 'f'",
				"Now put your right index finger on the 'j' key, which also has a bump, and type a 'j'",
				"Now take the rest of the fingers on your left hand and place them to the left of the 'f' key.  They should be touching 'a' 's' 'd' and 'f' - type this now",
				"Now take the rest of the fingers on your right hand and place them to the right of the 'j' key.  They should be touching 'j' 'k' 'l' and 'semicolon' - type this now",
				"Type 'a' 's' 'd' 'f' again",
				"Type 'j' 'k' 'l' 'semicolon' again",
				"Now backwards with your left hand - 'f' 'd' 's' 'a'",
				"Now backwards with your right hand - 'semicolon' 'l 'k' 'j'",
				"Now the entire home row - 'a' 's' 'd' 'f' 'j' 'k' 'l' 'semicolon'"],
	sequences: ["f",
				"j",
				"asdf",
				"jkl;",
				"asdf",
				"jkl;",
				"fdsa",
				";lkj",
				"asdfjkl;"],
	finish: "This lesson is now over.  Great job!"
};

var leftHandDrills = {
	name: "Left hand drills",
	description: "This gives you some practice typing words with your left hand",
	prompts: ["We will practice typing words with the left hand.  First find the 'f' key - it will have a bump on it.  Place your left index finger on the 'f' key, and type an 'f'",
				"Now take the rest of the fingers on your left hand and place them to the left of the 'f' key.  They should be touching 'a' 's' 'd' and 'f' - type this now",
				"Now type that backwards - 'f' 'd' 's' 'a'",
				"Now type fad",
				"Now type dad",
				"Now type add",
				"Now type sad",
				"Let's do 'a' 's' 'd' 'f' once more"],
	sequences: ["f",
				"asdf",
				"fdsa",
				"fad",
				"dad",
				"add",
				"sad",
				"asdf"],
	finish: "This lesson is now over.  Great job!"
};

var alphabet = {
	name: "Alphabet",
	description: "This will teach you to find the letters of the alphabet on the keyboard.",
	prompts: ["First type the letter a, then continue with the alphabet until the letter z"],
	sequences: ["abcdefghijklmnopqrstuvwxyz"],
	finish: "This lesson is now over.  Great job!"
};

var longWords = {
	name: "Long words",
	description: "This will challenge you by having you type long words.",
	prompts: ["Let's start with a musical instrument.  Type 'xylophone'",
				"How about a big animal?  Type 'elephant'",
				"What are you typing on? Type 'keyboard'",
				"Let's type 'refrigerator'",
				"Try 'vitamin'",
				"Next type 'messenger'",
				"Now try 'manufacturing'",
				"Next type 'seasonal'"],
	sequences: ["xylophone",
				"elephant",
				"keyboard",
				"refrigerator",
				"vitamin",
				"messenger",
				"manufacturing",
				"seasonal"],
	finish: "This lesson is now over.  Great job!"
};

var math = {
	name: "Math",
	description: "Some basic math",
	prompts: ["This will introduce you to the numbers on the keyboard.  Can you type 1, 2, 3?",
				"How about all the way from 1 to 9?",
				"Now do that backwards from 9 to 1",
				"Now let's do some simple addition.  What's 1 + 1?",
				"What is 2 + 2?",
				"How about 10 minus 7?",
				"6 minus 4?",
				"5 + 5?",
				"2 + 7?"],
	sequences: ["123",
				"123456789",
				"987654321",
				"2",
				"4",
				"3",
				"2",
				"10",
				"9"],
	finish: "This lesson is now over.  Great job!"
};

var lotsOfWords = {
	name: "Lots of words",
	description: "This will have you type many words.",
	prompts: ["Let's start with 'cup'",
				"Now try 'glass'",
				"Next type 'pen'",
				"Let's try 'soda'",
				"Type 'cat'",
				"How about 'dog'?",
				"'bird'?",
				"Let's talk about school now.  Can you type 'school'?",
				"Inside the school are desks.  Type 'desk'",
				"Next to each desk is a chair.  Type 'chair'",
				"Nobody likes this next one! Type 'homework'",
				"After school you go where? Type 'home'",
				"Next type 'candle'",
				"Now try 'car'",
				"Let's type 'can'",
				"How about 'book'",
				"Next type 'frog'",
				"Now try 'door'",
				"Next type 'road'",
				"How about 'sofa'",
				"What is beneath your feet? Type 'floor'",
				"This animal makes a funny sound.  Type 'monkey'",
				"Now type 'hero'"],
	sequences: ["cup",
				"glass",
				"pen",
				"soda",
				"cat",
				"dog",
				"bird",
				"school",
				"desk",
				"chair",
				"homework",
				"home",
				"candle",
				"car",
				"can",
				"book",
				"frog",
				"door",
				"road",
				"sofa",
				"floor",
				"monkey",
				"hero"],
	finish: "This lesson is now over.  Great job!"
};

var lessons = {
	homerow: homerow,
	alphabet: alphabet,
	leftHandDrills: leftHandDrills,
	longWords: longWords,
	math: math,
	lotsOfWords: lotsOfWords
};